
modLoader="javafml"

loaderVersion="[40,)" This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]]

modId="immersive_soils"

version = "${version}"

displayName="Immersive Soils"

logoFile="icon.png" #optional

credits="Ordana" #optional

authors="Ordana" #optional

itemIcon="immersive_soils:template" #catalogue icon
description='''
Immersive Soils Description
'''

[[dependencies.immersive_soils]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersive_soils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersive_soils]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.7.0,]"
    ordering="AFTER"
    side="BOTH"
