
modLoader="javafml"

loaderVersion="[40,)"

license="LGPLv3"

[[mods]]

modId="grounded"

version = "${version}"

displayName="Grounded"

logoFile="icon.gif" #optional

credits="Ordana" #optional

authors="Ordana, Kayla_the_bee" #optional

itemIcon="grounded:template" #catalogue icon
description='''
New soil variants to spice up your world
'''

[[dependencies.grounded]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grounded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.grounded]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.13.30,]"
    ordering="AFTER"
    side="BOTH"
