modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Silversmith-Mods/grounded/issues"
license = "LGPLv3"

[[mods]]
modId = "grounded"
version = "${version}"
displayName = "Grounded"
authors = "Ordana, Kayla_the_bee"
credits="Ordana, cassiancc" #optional
description = '''
New soil variants to spice up your world
'''
logoFile = "icon.png"

[[dependencies.grounded]]
modId = "neoforge"
type = "required"
versionRange = "[26,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grounded]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grounded]]
modId = "lithostitched"
type = "required"
versionRange = "[1)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "grounded.mixins.json"
